###
GET http://localhost:8080/test

###
GET http://localhost:8080/time

###
GET http://localhost:8080/echo/tra la la

###
POST http://localhost:8080/parameters
Content-Type: application/json

{
    "expression":"p|q&r|s"
}

###
POST http://localhost:8080/validate
Content-Type: application/json

{
  "expression":"p=>q",
  "parameters": [
    {
      "name": "p",
      "value": true
    },
    {
      "name": "q",
      "value": false
    }
  ]
}

###
POST http://localhost:8080/validate
Content-Type: application/json

{
  "expression":"p|p|p|p|p",
  "parameters": [
    {
      "name": "p",
      "value": true
    }
  ]
}
